/*
 * This file is generated by jOOQ.
 */
package com.emented.weblab4.jooq.tables.records;


import com.emented.weblab4.jooq.tables.RolesUsersRelation;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RolesUsersRelationRecord extends TableRecordImpl<RolesUsersRelationRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached RolesUsersRelationRecord
     */
    public RolesUsersRelationRecord() {
        super(RolesUsersRelation.ROLES_USERS_RELATION);
    }

    /**
     * Create a detached, initialised RolesUsersRelationRecord
     */
    public RolesUsersRelationRecord(Integer userId, Integer roleId) {
        super(RolesUsersRelation.ROLES_USERS_RELATION);

        setUserId(userId);
        setRoleId(roleId);
    }

    /**
     * Getter for <code>s336189.roles_users_relation.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>s336189.roles_users_relation.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>s336189.roles_users_relation.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>s336189.roles_users_relation.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(1, value);
    }

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RolesUsersRelation.ROLES_USERS_RELATION.USER_ID;
    }

    @Override
    public Field<Integer> field2() {
        return RolesUsersRelation.ROLES_USERS_RELATION.ROLE_ID;
    }

    @Override
    public Integer component1() {
        return getUserId();
    }

    @Override
    public Integer component2() {
        return getRoleId();
    }

    @Override
    public Integer value1() {
        return getUserId();
    }

    @Override
    public Integer value2() {
        return getRoleId();
    }

    @Override
    public RolesUsersRelationRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public RolesUsersRelationRecord value2(Integer value) {
        setRoleId(value);
        return this;
    }

    @Override
    public RolesUsersRelationRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }
}
