/*
 * This file is generated by jOOQ.
 */
package com.emented.weblab4.jooq;


import com.emented.weblab4.jooq.tables.Hits;
import com.emented.weblab4.jooq.tables.Users;
import com.emented.weblab4.jooq.tables.records.HitsRecord;
import com.emented.weblab4.jooq.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * s336189.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<HitsRecord> HITS_PKEY = Internal.createUniqueKey(Hits.HITS, DSL.name("hits_pkey"), new TableField[] { Hits.HITS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_EMAIL_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_email_key"), new TableField[] { Users.USERS.EMAIL }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<HitsRecord, UsersRecord> HITS__FK_USER = Internal.createForeignKey(Hits.HITS, DSL.name("fk_user"), new TableField[] { Hits.HITS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
}
