/*
 * This file is generated by jOOQ.
 */
package com.emented.weblab4.jooq;


import com.emented.weblab4.jooq.tables.Hits;
import com.emented.weblab4.jooq.tables.Users;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class S336189 extends SchemaImpl {

    /**
     * The reference instance of <code>s336189</code>
     */
    public static final S336189 S336189 = new S336189();
    private static final long serialVersionUID = 1L;
    /**
     * The table <code>s336189.hits</code>.
     */
    public final Hits HITS = Hits.HITS;

    /**
     * The table <code>s336189.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private S336189() {
        super("s336189", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
                Hits.HITS,
                Users.USERS
        );
    }
}
