/*
 * This file is generated by jOOQ.
 */
package com.emented.weblab4.jooq;


import com.emented.weblab4.jooq.tables.Hits;
import com.emented.weblab4.jooq.tables.Roles;
import com.emented.weblab4.jooq.tables.RolesUsersRelation;
import com.emented.weblab4.jooq.tables.Users;
import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class S336189 extends SchemaImpl {

    /**
     * The reference instance of <code>s336189</code>
     */
    public static final S336189 S336189 = new S336189();
    private static final long serialVersionUID = 1L;
    /**
     * The table <code>s336189.hits</code>.
     */
    public final Hits HITS = Hits.HITS;

    /**
     * The table <code>s336189.roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>s336189.roles_users_relation</code>.
     */
    public final RolesUsersRelation ROLES_USERS_RELATION = RolesUsersRelation.ROLES_USERS_RELATION;

    /**
     * The table <code>s336189.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private S336189() {
        super("s336189", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
                Sequences.HITS_ID_SEQ,
                Sequences.ROLES_ID_SEQ,
                Sequences.USERS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
                Hits.HITS,
                Roles.ROLES,
                RolesUsersRelation.ROLES_USERS_RELATION,
                Users.USERS);
    }
}
