/*
 * This file is generated by jOOQ.
 */
package com.emented.weblab4.jooq;


import com.emented.weblab4.jooq.tables.Hits;
import com.emented.weblab4.jooq.tables.Users;


/**
 * Convenience access to all tables in s336189.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>s336189.hits</code>.
     */
    public static final Hits HITS = Hits.HITS;

    /**
     * The table <code>s336189.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
